var quotes = [
  "TO CHANGE YOUR REALITY YOU MUST CHANGE YOUR MENTALITY",
  "I'll die to win, cause I was born to lose.",
  "The same people asking why you're doing it will be asking how you did it. So fuck a critic, stay committed to your vision.",
  'There is no strength without struggle',
  'Failure is success in progress.',
  'Ask yourself if what you are doing today is getting you closer to where you want to be tomorrow.',
  "Fuck excuses. You either want it or you don't.",
  "I'm moving different because I want different, old keys can't unlock new doors.",
  'No matter what happens, no matter how far you seem to be away from where you want to be, never stop believing that you will somehow make it. Have an unrelenting belief that things will work out, that the long road has a purpose.',
  'Your future is created by what you do today, not tomorrow.',
  "Don't fear failure. Fear being in the exact same place next year as you are today.",
  "Don't be afraid of being outnumbered. A lion walks alone while the sheep flock together.",
  'Surround yourself with people who push you to do and be better. No drama or negativity.',
  'When you love yourself, you attract better. You let the universe know that you deserve the best by treating yourself well. Everything starts with how you feel about yourself. Feel worthy, feel valuable,feel special, and feel deserving of receiving the best. It will happen for you.',
  'It never gets easier. You just get stronger.',
  "It's okay to live a life that other don't understand.",
  "There is so much silent work that you have to put in and nobody will ever know about, but you just have to do it. Do it without any applause or recognition, and keep going.",
  'The darkest of nights bring the brightest of stars. Keep going.',
  'Rock bottom has built more champions than privilege ever did.',
  'Every successful person you look up to was once just another kid with a dream.',
  'You gotta move different if you want different.',
  'The world is full of successful people who were told time and time again that their dream was impossible. They chose not to listen.',
  "Being the 1% means engineering your life so you never stop until you get what you want, and then you keep going until you get what's next. And then, you go for even more..",
  'Minor setbacks, make major comebacks.',
  'Work for a cause, not an applause.',
  "Look in the mirror. That's your competition.",
  'Stop wishing, Start doing.',
  'Pain is temporary. Quitting lasts forever.',
  "If it doesn't challenge you, it won't change you.",
  "Don't limit your challenges, challenge your limits.",
  "It isn't the hours you put in, but what you put in the hours.",
  'Success is right outside your comfort zone.',
  "If it's still in your mind, it's worth taking the risk.",
  'Spend more time on what gives you energy and less of what takes it away.',
  'Your only limit is you.',
  "It's not who you are that holds you behind, it's who you think you are not.",
  "If you feel like giving up, look back at how far you've come.",
  'Success starts with self-discipline.',
  'You never lose until you quit trying.',
  'Every failure is a step to success.',
  'The biggest room in life is the room for improvement.',
  "You never know what you have, until it's gone.",
  'Work while they sleep. Learn while they party. Save while they spend. Live like they dream.',
  'Sometimes good things fall apart so better things can fall together.',
  'Every morning you have two choices: continue to sleep with your dreams, or wake up and chase them.',
  "There's nothing more important in the world than loving yourself.",
  'Invest in your dreams. Grind now. Shine later.',
  "Don't mistake silence for weakness. Smart people don't plan big moves out loud.",
  "It's okay to make mistakes, it's not okay to not learn from them.",
  'Failure is your greatest teacher.'
]

function newQuote() {
  var randomNumber = Math.floor(Math.random() * (quotes.length));
  document.getElementById('quoteDisplay').innerHTML = quotes[randomNumber];
}
