var quotes = ["PARA CAMBIAR SU  REALIDAD DEBE CAMBIAR SU MENTALIDAD",
  "Moriré para ganar, porque nací para perder",
  "Las mismas personas que preguntan por qué lo hacen, preguntarán cómo lo hicieron. Así que jodan a un crítico, manténganse comprometidos con su visión",
  'No hay fuerza sin lucha',
  'El fracaso es el éxito en el progreso',
  "Pregúntate si lo que estás haciendo hoy es acercarte a donde quieres estar mañana.",
  "Joder excusas. O lo quieres o no",
  "Me muevo diferente porque quiero diferentes, las llaves viejas no pueden abrir puertas nuevas.",
  'No importa lo que pase, no importa cuán lejos parezca estar lejos de donde quiere estar, nunca deje de creer que de alguna manera lo logrará. Tener una creencia implacable de que las cosas saldrán bien, que el largo camino tiene un propósito.',
  'Tu futuro es creado por lo que haces hoy, no mañana.',
  "No temas al fracaso. Teme estar exactamente en el mismo lugar el año que viene hoy.",
  "No tengas miedo de ser superado en número. Un león camina solo mientras las ovejas se juntan.",
  'Rodéate de personas que te presionan para que hagas y seas mejor. Sin drama ni negatividad.',
  'Cuando te amas a ti mismo, atraes mejor. Dejas que el universo sepa que mereces lo mejor al tratarte bien. Todo comienza con cómo te sientes contigo mismo. Sentirse digno, sentirse valioso, sentirse especial y merecer recibir lo mejor. Te sucederá a ti.',
  'Nunca se hace más fácil. Te vuelves más fuerte ',
  "Está bien vivir una vida que otros no entienden",
  "Hay tanto trabajo silencioso que tienes que realizar y nadie lo sabrá nunca, pero solo tienes que hacerlo. Hazlo sin ningún aplauso o reconocimiento, y sigue adelante",
  'La noche más oscura trae las estrellas más brillantes. Sigue adelante.',
  'Rock bottom ha construido más campeones que el privilegio',
  'Cada persona exitosa a la que admiras fue una vez más un niño con un sueño',
  'Tienes que moverte diferente si quieres diferente',
  'El mundo está lleno de personas exitosas a las que se les dijo una y otra vez que su sueño era imposible. Eligieron no escuchar.',
  "Ser el 1% significa diseñar tu vida para que nunca te detengas hasta que obtengas lo que quieres, y luego sigas adelante hasta que obtengas lo que sigue. Y luego, vas por aún más ...",
  'Pequeños contratiempos, hacer grandes regresos',
  'Trabajar por una causa, no un aplauso',
  "Mirar en el espejo que es de su competencia.",
  'Deja de desear empieza a hacerlo.',
  'El dolor es temporal. Dejar de fumar dura para siempre',
  "Si no te desafía, no te cambiará",
  "No limites tus desafíos, desafía tus límites",
  "No son las horas que pones, sino lo que pones en las horas",
  'El éxito está justo fuera de tu zona de confort',
  "Si todavía está en su mente, vale la pena correr el riesgo",
  "Dedique más tiempo a lo que le da energía y menos a lo que le quita",
  'Tu único límite eres tú.',
  "No es quién eres lo que te detiene, sino quién crees que no eres.",
  "Si tienes ganas de rendirte, mira hacia atrás lo lejos que has llegado",
  'El éxito comienza con la autodisciplina.',
  'Nunca pierdes hasta que dejas de intentarlo.',
  'Cada fracaso es un paso hacia el éxito',
  "La sala más grande de la vida es la sala de mejora.",
  "Nunca sabes lo que tienes, hasta que se va.",
 'Trabaja mientras duermen. Aprende mientras festejan. Ahorre mientras gastan. Vive como sueña.',
  "A veces, las cosas buenas se desmoronan para que cosas mejores puedan juntarse",
  'Todas las mañanas tienes dos opciones: seguir durmiendo con tus sueños, o despertarte y perseguirlos',
  "No hay nada más importante en el mundo que amarte a ti mismo",
  'Invierte en tus sueños. Moler ahora. Brilla más tarde.',
  "No confundas el silencio con la debilidad. Las personas inteligentes no planean grandes movimientos en voz alta",
  "Está bien cometer errores, no está bien no aprender de ellos",
  'El fracaso es tu mejor maestro.'

]

function newQuote() {
  var randomNumber = Math.floor(Math.random() * (quotes.length));
  document.getElementById('quoteDisplay').innerHTML = quotes[randomNumber];
}
